site_name: ODIN
theme: material
repo_url: https://github.com/ministerio-produccion/odin
extra:
  logo: 'images/logo.png'
  social:
    - type: 'github'
      link: 'https://github.com/ministerio-produccion'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
pages:
    - 'Home': 'index.md'
    - 'Key Features': 'key-features.md'
    - 'Arquitectura': 'arquitectura.md'
    - 'Codigo Fuente': 'codigo-fuente.md'
    - 'Metodología': 'metodologia.md'
    - 'Entidades': 'entidades.md'
    - 'Responses': 'responses.md'
    - Referencias:
        - 'HTTP Status Codes': 'references/status-codes.md'
    - Links:
        - 'Backend': 'links/backend.md'
        - 'Frontend': 'links/frontend.md'
